-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 22:35:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BolsaFamilaDW
-- -----------------------------------------------------
-- Data Warehouse para o programa Bolsa Familia
DROP SCHEMA IF EXISTS `BolsaFamilaDW` ;

-- -----------------------------------------------------
-- Schema BolsaFamilaDW
--
-- Data Warehouse para o programa Bolsa Familia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BolsaFamilaDW` DEFAULT CHARACTER SET utf8 ;
USE `BolsaFamilaDW` ;

-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`DimTempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`DimTempo` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`DimTempo` (
  `idDimTempo` INT NOT NULL AUTO_INCREMENT,
  `ANO` VARCHAR(4) NOT NULL,
  `MES` VARCHAR(2) NOT NULL,
  `DIA` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idDimTempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`DimMunicipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`DimMunicipio` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`DimMunicipio` (
  `idDimCidade` INT NOT NULL AUTO_INCREMENT,
  `COD_SIAFI` BIGINT(10000) NOT NULL,
  `MUNICIPIO` VARCHAR(45) NOT NULL,
  `ESTADO` VARCHAR(20) NOT NULL,
  `REGIAO` VARCHAR(20) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`idDimCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`DimFavorecido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`DimFavorecido` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`DimFavorecido` (
  `idDimFavorecido` INT NOT NULL,
  `NIS` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NULL,
  PRIMARY KEY (`idDimFavorecido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`DimFuncao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`DimFuncao` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`DimFuncao` (
  `idDimFuncao` INT NOT NULL,
  `COD_FUNCAO` BIGINT(10000) NOT NULL,
  `COD_SUBFUNCAO` BIGINT(10000) NOT NULL,
  `COD_AÇÃO` BIGINT(10000) NOT NULL,
  PRIMARY KEY (`idDimFuncao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`DimFonte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`DimFonte` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`DimFonte` (
  `idDimFonte` INT NOT NULL,
  `FONTE` VARCHAR(45) NOT NULL,
  `FINALIDADE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDimFonte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BolsaFamilaDW`.`FatBolsaFamilia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BolsaFamilaDW`.`FatBolsaFamilia` ;

CREATE TABLE IF NOT EXISTS `BolsaFamilaDW`.`FatBolsaFamilia` (
  `DimMunicipio_idDimCidade` INT NOT NULL,
  `DimFavorecido_idDimFavorecido` INT NOT NULL,
  `DimFuncao_idDimFuncao` INT NOT NULL,
  `DimFonte_idDimFonte` INT NOT NULL,
  `DimTempo_idDimTempo` INT NOT NULL,
  `VALOR_PARCELA` FLOAT NOT NULL,
  PRIMARY KEY (`DimMunicipio_idDimCidade`, `DimFavorecido_idDimFavorecido`, `DimFuncao_idDimFuncao`, `DimFonte_idDimFonte`, `DimTempo_idDimTempo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
